name: flutter_stockfish_example_common
description: Demonstrates how to use the flutter_stockfish plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_stockfish:
    path: ../flutter_stockfish
